### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by syrnick** [bminer/node-static-asset#17]
Can you add a license file? Thanks!

**Comment by Fonger** [comment]
+1
2015/5/5 上午4:44於 "Alexander Sorokin" <notifications@github.com>寫道：

**Comment by bminer** [comment]
Sure thing.  Gimme one sec... I plan on using the MIT license.

**Comment by bminer** [comment]
Closed as of cd7bbe1fcbc6d5e2e1738c7f4b9b823471222097
